#!/bin/bash

# Clippy Website - GitHub Deployment Helper
# This script helps you deploy to GitHub Pages

echo "🚀 Clippy Website - GitHub Pages Deployment"
echo "=========================================="
echo ""

# Check if we're in the right directory
if [ ! -f "index.html" ] || [ ! -f "CNAME" ]; then
    echo "❌ Error: Must run from clippy-website directory"
    echo "   Current directory: $(pwd)"
    exit 1
fi

echo "✅ Website files verified"
echo ""

# Show current git status
echo "📊 Git Status:"
git status --short
echo ""

echo "📋 DEPLOYMENT STEPS:"
echo "==================="
echo ""
echo "1. 📝 CREATE GITHUB REPOSITORY"
echo "   ---------------------------"
echo "   • Go to: https://github.com"
echo "   • Click '+' → 'New repository'"
echo "   • Name: clippy-website"
echo "   • Make it PUBLIC"
echo "   • DO NOT initialize with README"
echo ""
echo "2. 🔗 CONNECT TO GITHUB"
echo "   --------------------"
echo "   Run these commands (replace YOUR_USERNAME):"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/clippy-website.git"
echo "   git push -u origin main"
echo ""
echo "3. ⚙️ ENABLE GITHUB PAGES"
echo "   ---------------------"
echo "   • Go to: github.com/YOUR_USERNAME/clippy-website"
echo "   • Settings → Pages"
echo "   • Source: 'Deploy from a branch'"
echo "   • Branch: main, Folder: / (root)"
echo "   • Click Save"
echo ""
echo "4. 🌐 SET CUSTOM DOMAIN"
echo "   --------------------"
echo "   • In Pages settings, add: clippy.world"
echo "   • Click Save"
echo ""
echo "5. 🔧 CONFIGURE DNS"
echo "   ----------------"
echo "   Add these A records at your domain registrar:"
echo ""
echo "   185.199.108.153"
echo "   185.199.109.153"
echo "   185.199.110.153"
echo "   185.199.111.153"
echo ""
echo "6. ⏳ WAIT FOR PROPAGATION"
echo "   ----------------------"
echo "   • Usually 5-60 minutes"
echo "   • Check: https://whatsmydns.net/#A/clippy.world"
echo "   • Live at: https://clippy.world"
echo ""

# Show ready-to-use commands
echo "💻 READY-TO-USE COMMANDS:"
echo "========================"
echo ""
echo "# Add GitHub remote (replace YOUR_USERNAME):"
echo "git remote add origin https://github.com/YOUR_USERNAME/clippy-website.git"
echo ""
echo "# Push to GitHub:"
echo "git push -u origin main"
echo ""
echo "# Check remote:"
echo "git remote -v"
echo ""
echo "# View all files:"
echo "ls -la"
echo ""
echo "# Test locally:"
echo "python3 -m http.server 8000"
echo "# Then open: http://localhost:8000"
echo ""

echo "🎯 QUICK START:"
echo "=============="
echo "1. Create GitHub repo: clippy-website (Public)"
echo "2. Run: git remote add origin https://github.com/YOUR_USERNAME/clippy-website.git"
echo "3. Run: git push -u origin main"
echo "4. Enable GitHub Pages in repo settings"
echo "5. Add custom domain: clippy.world"
echo "6. Configure DNS at domain registrar"
echo ""

echo "📞 NEED HELP?"
echo "============="
echo "• Full guide: GITHUB_DEPLOYMENT_GUIDE.md"
echo "• Deployment options: DEPLOYMENT.md"
echo "• Test locally first with: python3 -m http.server 8000"
echo ""

echo "✅ Your website is ready for deployment!"
echo "   Total cost: FREE (GitHub Pages)"
echo "   Time: 15-30 minutes"
echo ""